### ISSUE TITLE
Can I call an R function and get the output in json using HTTP REST API

### ISSUE THREAD

**Issue by GoChartingAdmin** [MarkEdmondson1234/serverless-R-API-appengine#2]
Hi,

I have a Javascript App called "www.gocharting.com" which specializes in Technical Analysis of stocks and charting.  It is housed in aws and I want to leverage the blotter and quanstrat packages in R to create a backtesting module in my app.  I want the client to call a HTTP API which can call the R functions and codes to output the result of the backtest back to the client in json format

Was wondering if you package can bridge the gap in my use case.  If yes, please refer me to some sample demo code which will enable me to call a simple R function from JS and return the output back in json.  I know I could use OpenCPU but I found it fairly difficult to use.

Regards
GC

**Comment by MarkEdmondson1234** [comment]
Hi, well OpenCPU is a lot more tested for your kind of application, you may want to reference [this solution](http://code.markedmondson.me/predictClickOpenCPU/) that uses OpencPU.  End of the day its creating an R package, uploading it to GitHub and calling the OpenCPU js library that takes care of stuff for you. 

This solution uses [plumber](https://github.com/trestletech/plumber) on the App Engine stack - generally I would suggest keeping to the tech stack you are using so you may want to find an Amazon equivalent.

All that being said you can call the app engine URL like any other API - an example of using jQuery POST is here, although you could also do GET depending on how you configure you R code.  (Adapted from [this example](https://github.com/MarkEdmondson1234/ga-bq-stream))
```js
<script>

  var result = jQuery.post("https://YOUR-PROJECT-ID.appspot.com/your-r-api", {"q":JSON.stringify(args)});
 /// do something with result
....
</script>

**Comment by GoChartingAdmin** [comment]
Wow. Excellent.  This is cool stuff
