### ISSUE TITLE
Error while deploying R using plumber in Google App Engine Flex with Docker

### ISSUE THREAD

**Issue by ashishsr123** [MarkEdmondson1234/serverless-R-API-appengine#4]
Hello, 
I want to server R model using App Engine.
I am following your example, but stuck. I tried several methods but still have issues. Any guidance on this issue?

Please refer to my code
**app.yaml**

```
runtime: custom
env: flex
```
**Dockerfile**

```
FROM gcr.io/gcer-public/plumber-appengine
LABEL maintainer="mark"

RUN R -e "install.packages(c('plumber'), repos='http://cran.rstudio.com/')"

WORKDIR /payload/
COPY [".", "./"]

EXPOSE 8080
ENTRYPOINT ["R", "-e", "pr <- plumber::plumb(commandArgs()[4]); pr$run(host='0.0.0.0', port=8080)"]
CMD ["schedule.R"]
```

**schedule.R**

```

#* @get /demoR
get_predict_length <- function(){
      
  dataset <- iris
  
  # create the model
  model <- lm(Petal.Length ~ Petal.Width, data = dataset)
  petal_width = "0.4"
  
  #petal_width = '0.4'
  # convert the input to a number
  petal_width <- as.numeric(petal_width)
  
  #create the prediction data frame
  prediction_data <- data.frame(Petal.Width=petal_width)
  
  # create the prediction
  predict(model,prediction_data)
}
```
Final output in logs

Stackdriver logs show:
![image](https://user-images.githubusercontent.com/10070119/64014648-49eb1780-cb40-11e9-8188-e525f4f79e2b.png)

when I click on app engine version , I get below message:
**This site can’t be reached**

Note: I tried a modified code but got deployment error before ,details: 
[https://stackoverflow.com/questions/57724224/error-while-deploying-r-using-plumber-in-google-app-engine-flex-with-docker](https://stackoverflow.com/questions/57724224/error-while-deploying-r-using-plumber-in-google-app-engine-flex-with-docker)

Thanks
Ashishsr123

**Comment by MarkEdmondson1234** [comment]
This is a bit old so you may want to try with the Docker/plumber implementation here first:
https://github.com/MarkEdmondson1234/cloudRunR

I would also suggest that Cloud Run is an easier service to deploy on, which is also described at the link above.

**Comment by ashishsr123** [comment]
Ok Mark will try that also..but still wondering what is the issue in my app engine deployment , as I cannot reach site. I added my ip in firewall approve list also.

**Comment by MarkEdmondson1234** [comment]
Can you try returning a 200 status code on the root page? e.g. / - it can just say "Hello World" or similar.

**Comment by ashishsr123** [comment]
Thanks I was able to make it work but whenever I use 
FROM gcr.io/deeplearning-platform-release/r-cpu  # google provided image , my deployment fails rest all remains same.

**Error message:**

![image](https://user-images.githubusercontent.com/10070119/64244642-0b31d480-cf27-11e9-8b4c-08d496c3cedf.png)

Note:
Initially I got error message stating to increase 'app_start_timeout_sec' , I gradually increased from 300 to 1800 but now get above error message.

Ashishsr123

**Comment by MarkEdmondson1234** [comment]
That looks like a separate issue, probably related that the image you are using is not compatible with the script?  I have not used `gcr.io/deeplearning-platform-release/r-cpu` so would suggest looking at its build script to see if its suitable.  For instance, have you installed plumber?

**Comment by ashishsr123** [comment]
my R script is very simple and when I do docker run .. everything runs fine and plumber is also installed , as its mentioned in my dockerfile.

**Comment by MarkEdmondson1234** [comment]
I'm sorry, it looks ok.  Perhaps look in the logs, or try asking on the App Engine flexible forums.

**Comment by ashishsr123** [comment]
Thanks for you time Mark :-)
